### ISSUE TITLE
Refactor pipelines

### ISSUE THREAD

**Issue by cemilcengiz** [obss/trapper#32]
HuggingFace transformers' pipelinies underwent in a major major refactor in [v4.11.0](https://github.com/huggingface/transformers/releases/tag/v4.11.0). Thanks to the new design, we can refactor our pipeline factory and existing pipelines as well as possibly wrapping the pipeline as a Registrable class. However, [allennlp's latest release](https://pypi.org/project/allennlp/2.7.0/) does not have that yet although their master branch has. Therefore, we may need to wait till their new release (I expect it won't take long) or use [that commit](https://github.com/allenai/allennlp/commit/a63e28c24d091fb371011f644fec3ebd29bfbb7e) to prevent a dependency mismatch.

**Comment by devrimcavusoglu** [comment]
We have several options on integration.

1. To use the experiment config for training also for the pipeline.
  a. To include pipeline configuration inside the training config (e.g with new "pipeline" key) and we can cut off/ignore this `"pipeline"` keyword on trainer construction (with some utility function here, e.g first read the config, pop the key "pipeline" and then feed to trainer constructor).
  b. Implement a utility for pipeline (like we already have `create_pipeline_from_checkpoint`), and this utility can construct pipeline parameters from the training parameters (e.g data components under `dataset_loader` for example are converted to lone entities to be fed) direct instantiation from parameters this way (like preprocessing config parameters and then construct using `from_params`).
2. Separate configuration file for pipeline, this is what suggested in (1a) in a different file (without being under `"pipeline"` key anymore).

I think (1a) is not good as it brings processing not only for trainer, but also for pipeline, and also there is redundancy caused by duplication. 

I think (1b), though, is way better option, it does not change the interface `create_pipeline_from_checkpoint` and just bring a refactor to this helper function. The problem with this is if we were add another argument or keyword argument to the `Pipeline`, then we also need to manually handle this at that point.

(2) is the most reliable choice I think, and some advantages are pipeline can now be more modular (e.g data_adapters does not necessarilty be the same with trainer), but it has some drawbacks such as two config files instead of one, potential duplication among the files.

All in all, Pipeline and Trainer share some arguments, but they are not subset of each other. Wdyt ? @cemilcengiz @Sophylax @SecilOzkSen
